FIND_PATH(FREETYPE_INCLUDE_DIR_ft2build ft2build.h 
  PATHS
  ${FREETYPE_DIR}
  NO_DEFAULT_PATH
  PATH_SUFFIXES include    
)


FIND_PATH(FREETYPE_INCLUDE_DIR_freetype2 freetype/config/ftheader.h 
  ${FREETYPE_DIR}/include
  NO_DEFAULT_PATH
)

if(WIN32)
    FIND_LIBRARY(FREETYPE_LIBRARY_DEBUG
      NAMES freetype libfreetype freetype219
      PATHS
      ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG}
      NO_DEFAULT_PATH
      #PATH_SUFFIXES lib64 lib 
    )
    FIND_LIBRARY(FREETYPE_LIBRARY_RELEASE
      NAMES freetype libfreetype freetype219
      PATHS
      ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE}
      NO_DEFAULT_PATH
      #PATH_SUFFIXES lib64 lib 
    )
    set(FREETYPE_LIBRARY "debug ${FREETYPE_LIBRARY_DEBUG} optimized ${FREETYPE_LIBRARY_RELEASE}" CACHE INTERNAL "")
    message(${FREETYPE_LIBRARY})
else()
    FIND_LIBRARY(FREETYPE_LIBRARY 
      NAMES freetype libfreetype freetype219
      PATHS
      ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
      NO_DEFAULT_PATH
      #PATH_SUFFIXES lib64 lib 
    )
endif()

IF(FREETYPE_INCLUDE_DIR_ft2build AND FREETYPE_INCLUDE_DIR_freetype2)
  SET(FREETYPE_INCLUDE_DIRS "${FREETYPE_INCLUDE_DIR_ft2build};${FREETYPE_INCLUDE_DIR_freetype2}")
ENDIF(FREETYPE_INCLUDE_DIR_ft2build AND FREETYPE_INCLUDE_DIR_freetype2)


SET(FREETYPE_FOUND "NO")
IF(FREETYPE_LIBRARY AND FREETYPE_INCLUDE_DIRS)
  SET(FREETYPE_FOUND "YES")
ENDIF(FREETYPE_LIBRARY AND FREETYPE_INCLUDE_DIRS)
